# Configuration
config:
  line-length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
      - br

globs:
  - "**/*.md"

ignores:
  - "docs/index.md" # First line isn't h1 ('#') so always get a complaint
  - "tmp/"
  - "paper.md"
  - ".venv/"
  - ".github/CONTRIBUTING.md"
  - "docs/markdown.md"
  - "docs/api/*.md"

fix: true
